// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1b9SETGKb-2t_YN7Luy2MJoaVbab9okI',
    appId: '1:195865332091:web:77ca0a8e8c359a7a54d5de',
    messagingSenderId: '195865332091',
    projectId: 'very-berries',
    authDomain: 'very-berries.firebaseapp.com',
    storageBucket: 'very-berries.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTGIERBEtGJfr7Z_WT-SA2YG0wx2OOiQU',
    appId: '1:195865332091:android:69394d1bd12f9fad54d5de',
    messagingSenderId: '195865332091',
    projectId: 'very-berries',
    storageBucket: 'very-berries.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZHiwY-3YlJDGwuez5tzUHm8oLH0V1hFw',
    appId: '1:195865332091:ios:cdacb2a4c48fa4f354d5de',
    messagingSenderId: '195865332091',
    projectId: 'very-berries',
    storageBucket: 'very-berries.firebasestorage.app',
    iosBundleId: 'com.lenayoo.veryberries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZHiwY-3YlJDGwuez5tzUHm8oLH0V1hFw',
    appId: '1:195865332091:ios:355c41df3542c17c54d5de',
    messagingSenderId: '195865332091',
    projectId: 'very-berries',
    storageBucket: 'very-berries.firebasestorage.app',
    iosBundleId: 'com.example.veryberries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1b9SETGKb-2t_YN7Luy2MJoaVbab9okI',
    appId: '1:195865332091:web:50f2fb373336fbbc54d5de',
    messagingSenderId: '195865332091',
    projectId: 'very-berries',
    authDomain: 'very-berries.firebaseapp.com',
    storageBucket: 'very-berries.firebasestorage.app',
  );
}
